/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:474f8cfd-ce1d-405c-b9d6-04e424fdaf5e",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_MynuXPKKx",
    "aws_user_pools_web_client_id": "1hk16qcutm3109l7fibvfi53v3",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://cxeuew6shbfx7g2lddgtzgt4fe.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xc6gwm5b4bf5jarbpk74d37wzu",
    "aws_user_files_s3_bucket": "amplifyapp075f9f232c024b23a7466c4095a4cfa6190406-staging",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
